<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DalamudLibPath>$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
    <PluginVersion>2.2.0.10</PluginVersion>
  </PropertyGroup>
  
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AssemblyName>orchestrion</AssemblyName>
    <AssemblyTitle>orchestrion</AssemblyTitle>
    <Product>orchestrion</Product>
    <Authors>Meli, perchbird</Authors>
    <Copyright>Copyright ©  2021</Copyright>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Version>$(PluginVersion)</Version>
    <FileVersion>$(PluginVersion)</FileVersion>
    <AssemblyVersion>$(PluginVersion)</AssemblyVersion>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Dalamud">
      <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FFXIVClientStructs">
      <HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ImGui.NET">
      <HintPath>$(DalamudLibPath)ImGui.NET.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ImGuiScene">
      <HintPath>$(DalamudLibPath)ImGuiScene.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Lumina">
      <HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(DalamudLibPath)Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="CheapLoc">
      <HintPath>$(DalamudLibPath)CheapLoc.dll</HintPath>
      <Private>False</Private>
    </Reference>
    
    <PackageReference Include="DalamudPackager" Version="11.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ContentWithTargetPath Include="Data\xiv_bgm_en.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>xiv_bgm_en.csv</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="Data\xiv_bgm_de.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>xiv_bgm_de.csv</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="Data\xiv_bgm_fr.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>xiv_bgm_fr.csv</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="Data\xiv_bgm_ja.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>xiv_bgm_ja.csv</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="Data\xiv_bgm_zh.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>xiv_bgm_zh.csv</TargetPath>
    </ContentWithTargetPath>
    <ContentWithTargetPath Include="Data\xiv_bgm_metadata.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>xiv_bgm_metadata.csv</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="UI\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Loc\de.json" />
    <EmbeddedResource Include="Loc\de.json" />
    <None Remove="Loc\en.json" />
    <EmbeddedResource Include="Loc\en.json" />
    <None Remove="Loc\es.json" />
    <EmbeddedResource Include="Loc\es.json" />
    <None Remove="Loc\fr.json" />
    <EmbeddedResource Include="Loc\fr.json" />
    <None Remove="Loc\it.json" />
    <EmbeddedResource Include="Loc\it.json" />
    <None Remove="Loc\ja.json" />
    <EmbeddedResource Include="Loc\ja.json" />
    <None Remove="Loc\zh.json" />
    <EmbeddedResource Include="Loc\zh.json" />
  </ItemGroup>
</Project>